### ISSUE TITLE
cMD3 updates

### ISSUE THREAD

**Issue by lwaldron** [cmirzayi/EpiForBioWorkshop2021#2]
curatedMetagenomicData code is broken by new dataset naming conventions in the recent cMD3 update, and needs to be updated. Here is documentation for the new version:

* main article (go here): https://waldronlab.io/curatedMetagenomicData/articles/curatedMetagenomicData.html
* available studies: https://waldronlab.io/curatedMetagenomicData/articles/articles/available-studies.html 
* version 3: https://waldronlab.io/curatedMetagenomicData/articles/articles/version-three.html

**Comment by cmirzayi** [comment]
Vignette has been updated to use cMD3.
